resources:
- ../base
namePrefix: configMapGenerator-

configMapGenerator:
- name: configmap-file
  files:
  - application.properties
- name: configmap-env
  envs:
  - .env
- name: configmap-literals
  literals:
  - Literals=generatedLiterals