apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: configmap-file
        configMap:
          name: configmap-file
      - name: configmap-env
        configMap:
          name: configmap-env
      - name: configmap-literals
        configMap:
          name: configmap-literals
      - name: secret-file
        secret:
          secretName: secret-file
      - name: secret-literals
        secret:
          secretName: secret-literals